/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function AmbuStill(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF("/AmbuStill.glb");
	const { actions } = useAnimations(animations, group);

	return (
		<group
			scale={10}
			position={[0, -3, 0]}
			ref={group}
			{...props}
			dispose={null}>
			<group name='Scene'>
				<group name='SMORE_RIG'>
					<primitive object={nodes.Root} />
					<primitive object={nodes.elbowikL} />
					<primitive object={nodes.handikL} />
					<primitive object={nodes.elbowikR} />
					<primitive object={nodes.handikR} />
					<primitive object={nodes.kneeikL} />
					<primitive object={nodes.footikL} />
					<primitive object={nodes.kneeikR} />
					<primitive object={nodes.footikR} />
				</group>
				<group name='Empty' />
				<group
					name='terreno_pincy'
					position={[-0.52, -0.79, 0.41]}
					rotation={[0, 0, -0.06]}
				/>
				<group name='head' position={[0, 0.35, 0.01]}>
					<mesh name='Sphere004' geometry={nodes.Sphere004.geometry}>
						<meshPhysicalMaterial color={0xd4d4d8} />
					</mesh>
					<mesh
						name='Sphere004_1'
						geometry={nodes.Sphere004_1.geometry}
						material={materials["Material.002"]}
					/>
					<mesh
						name='coin_'
						geometry={nodes.coin_.geometry}
						material={materials["Fine Gold"]}
						morphTargetDictionary={nodes.coin_.morphTargetDictionary}
						morphTargetInfluences={nodes.coin_.morphTargetInfluences}
						position={[-0.05, -0.02, 0.07]}
						rotation={[Math.PI / 2, 0, 0]}
						scale={[1.05, 1, 1.05]}
					/>
					<mesh
						name='coin_001'
						geometry={nodes.coin_001.geometry}
						material={materials["Fine Gold"]}
						morphTargetDictionary={nodes.coin_001.morphTargetDictionary}
						morphTargetInfluences={nodes.coin_001.morphTargetInfluences}
						position={[0.04, -0.02, 0.07]}
						rotation={[Math.PI / 2, 0, 0]}
						scale={[1.05, 1, 1.05]}
					/>
					<mesh
						name='ears'
						geometry={nodes.ears.geometry}
						material={materials.Material}
						position={[0, 0.1, -0.01]}
						rotation={[Math.PI / 2, 0, 0]}
					/>
				</group>
				<mesh
					name='StaffSPLINE'
					geometry={nodes.StaffSPLINE.geometry}
					material={materials["Fine Gold"]}
					position={[0.27, 0.27, 0.02]}
					rotation={[2.6, -0.83, 1.02]}
					scale={0.57}>
					<mesh
						name='Sphere'
						geometry={nodes.Sphere.geometry}
						material={materials["Fine Gold"]}
						position={[0, 0, -0.01]}
					/>
					<mesh
						name='Spiral'
						geometry={nodes.Spiral.geometry}
						material={materials["Fine Gold"]}
						position={[0, 0, 0.33]}
						rotation={[0, 0, Math.PI / 2]}
					/>
				</mesh>
				<group name='armor_arm_L'>
					<skinnedMesh
						name='Roundcube012'
						geometry={nodes.Roundcube012.geometry}
						material={materials["Metal blau"]}
						skeleton={nodes.Roundcube012.skeleton}
					/>
					<skinnedMesh
						name='Roundcube012_1'
						geometry={nodes.Roundcube012_1.geometry}
						material={materials["boletes grogues"]}
						skeleton={nodes.Roundcube012_1.skeleton}
					/>
				</group>
				<group name='_LEG_L'>
					<skinnedMesh
						name='Cylinder002'
						geometry={nodes.Cylinder002.geometry}
						material={materials["Metal scratched"]}
						skeleton={nodes.Cylinder002.skeleton}
					/>
					<skinnedMesh
						name='Cylinder002_1'
						geometry={nodes.Cylinder002_1.geometry}
						material={materials["Metal.claret"]}
						skeleton={nodes.Cylinder002_1.skeleton}
					/>
				</group>
				<group name='_LEG_R'>
					<skinnedMesh
						name='Cylinder001'
						geometry={nodes.Cylinder001.geometry}
						material={materials["Metal scratched"]}
						skeleton={nodes.Cylinder001.skeleton}
					/>
					<skinnedMesh
						name='Cylinder001_1'
						geometry={nodes.Cylinder001_1.geometry}
						material={materials["Metal.claret"]}
						skeleton={nodes.Cylinder001_1.skeleton}
					/>
				</group>
				<group name='Body'>
					<skinnedMesh
						name='Roundcube008'
						geometry={nodes.Roundcube008.geometry}
						material={materials["Metal scratched"]}
						skeleton={nodes.Roundcube008.skeleton}
					/>
					<skinnedMesh
						name='Roundcube008_1'
						geometry={nodes.Roundcube008_1.geometry}
						material={materials["Metal.claret"]}
						skeleton={nodes.Roundcube008_1.skeleton}
					/>
				</group>
				<group name='_arm_R'>
					<skinnedMesh
						name='Roundcube003'
						geometry={nodes.Roundcube003.geometry}
						material={materials["Metal scratched"]}
						skeleton={nodes.Roundcube003.skeleton}
					/>
					<skinnedMesh
						name='Roundcube003_1'
						geometry={nodes.Roundcube003_1.geometry}
						material={materials["Metal.claret"]}
						skeleton={nodes.Roundcube003_1.skeleton}
					/>
				</group>
				<skinnedMesh
					name='armor'
					geometry={nodes.armor.geometry}
					material={materials["Metal blau"]}
					skeleton={nodes.armor.skeleton}
				/>
				<skinnedMesh
					name='Grid_body'
					geometry={nodes.Grid_body.geometry}
					material={materials["Metal.claret"]}
					skeleton={nodes.Grid_body.skeleton}
				/>
				<skinnedMesh
					name='decoration_arm_R'
					geometry={nodes.decoration_arm_R.geometry}
					material={materials["Metal.claret"]}
					skeleton={nodes.decoration_arm_R.skeleton}
				/>
				<skinnedMesh
					name='grid_leg_L'
					geometry={nodes.grid_leg_L.geometry}
					material={materials["Metal.claret"]}
					skeleton={nodes.grid_leg_L.skeleton}
				/>
				<skinnedMesh
					name='grid_leg_R'
					geometry={nodes.grid_leg_R.geometry}
					material={materials["Metal.claret"]}
					skeleton={nodes.grid_leg_R.skeleton}
				/>
				<skinnedMesh
					name='shoudler_pad'
					geometry={nodes.shoudler_pad.geometry}
					material={materials["Metal blau"]}
					skeleton={nodes.shoudler_pad.skeleton}
				/>
				<group name='_arm_L'>
					<skinnedMesh
						name='Torus'
						geometry={nodes.Torus.geometry}
						material={materials["Metal.claret"]}
						skeleton={nodes.Torus.skeleton}
					/>
					<skinnedMesh
						name='Torus_1'
						geometry={nodes.Torus_1.geometry}
						material={materials["Metal scratched"]}
						skeleton={nodes.Torus_1.skeleton}
					/>
				</group>
				<group name='armor_arm_R'>
					<skinnedMesh
						name='Roundcube015'
						geometry={nodes.Roundcube015.geometry}
						material={materials["Metal blau"]}
						skeleton={nodes.Roundcube015.skeleton}
					/>
					<skinnedMesh
						name='Roundcube015_1'
						geometry={nodes.Roundcube015_1.geometry}
						material={materials["boletes grogues"]}
						skeleton={nodes.Roundcube015_1.skeleton}
					/>
				</group>
				<skinnedMesh
					name='decoration_arm_L'
					geometry={nodes.decoration_arm_L.geometry}
					material={materials["Metal.claret"]}
					skeleton={nodes.decoration_arm_L.skeleton}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/AmbuStill.glb");
