/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import * as THREE from "three";
export function AmbuTricks(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF("/AmbuTricks.glb");
	const { actions } = useAnimations(animations, group);
	return (
		<group scale={6} ref={group} {...props} dispose={null}>
			<group name='Scene'>
				<group
					name='terreno_pincy'
					position={[-0.52, -0.79, 0.41]}
					rotation={[0, 0, -0.06]}
				/>
				<group
					name='Reference001'
					position={[0.37, 0.01, 0.04]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.2}>
					<group
						name='Hips'
						position={[0.28, -0.06, -0.91]}
						rotation={[-1.57, -0.06, 0.03]}>
						<group
							name='RightUpLeg'
							position={[-0.08, 0, 0]}
							rotation={[-0.2, -0.04, -0.25]}>
							<group
								name='RightLeg'
								position={[0, -0.43, 0]}
								rotation={[0.12, -0.05, -0.01]}>
								<group
									name='RightFoot'
									position={[0, -0.42, 0]}
									rotation={[0.02, -0.14, 0.03]}>
									<group name='RightToeBase' position={[0, -0.07, 0.15]} />
								</group>
							</group>
						</group>
						<group
							name='LeftUpLeg'
							position={[0.08, 0, 0]}
							rotation={[0.12, 0.33, 0.14]}>
							<group
								name='LeftLeg'
								position={[0, -0.43, 0]}
								rotation={[-0.01, 0.04, 0]}>
								<group
									name='LeftFoot'
									position={[0, -0.42, 0]}
									rotation={[-0.03, 0.38, 0.07]}>
									<group name='LeftToeBase' position={[0, -0.07, 0.15]} />
								</group>
							</group>
						</group>
						<group
							name='Spine'
							position={[0, 0.1, -0.01]}
							rotation={[0.03, -0.04, 0.01]}>
							<group
								name='Spine1'
								position={[0, 0.11, 0]}
								rotation={[-0.09, -0.02, 0]}>
								<group
									name='Spine2'
									position={[0, 0.1, 0]}
									rotation={[0.01, -0.02, 0]}>
									<group
										name='Spine3'
										position={[0, 0.1, 0]}
										rotation={[0.11, -0.01, 0]}>
										<group
											name='LeftShoulder'
											position={[0.03, 0.08, 0]}
											rotation={[0.17, -0.11, -0.09]}>
											<group
												name='LeftArm'
												position={[0.14, 0, 0]}
												rotation={[-0.07, -0.52, -0.8]}>
												<group
													name='LeftForeArm'
													position={[0.31, 0, 0]}
													rotation={[0.07, -0.28, -0.14]}>
													<group
														name='LeftHand'
														position={[0.25, 0, 0]}
														rotation={[-0.03, -0.14, -0.19]}
													/>
												</group>
											</group>
										</group>
										<group
											name='RightShoulder'
											position={[-0.03, 0.08, 0]}
											rotation={[0.21, 0.05, 0.06]}>
											<group
												name='RightArm'
												position={[-0.14, 0, 0]}
												rotation={[0.18, 0.59, 0.82]}>
												<group
													name='RightForeArm'
													position={[-0.31, 0, 0]}
													rotation={[-0.36, 0.31, 0.18]}>
													<group
														name='RightHand'
														position={[-0.25, 0, 0]}
														rotation={[-0.01, 0.03, 0.07]}
													/>
												</group>
											</group>
										</group>
										<group
											name='Neck'
											position={[0, 0.14, 0]}
											rotation={[0.39, 0.12, -0.06]}>
											<group
												name='Head'
												position={[0, 0.09, 0]}
												rotation={[0.09, 0.24, -0.08]}
											/>
										</group>
									</group>
								</group>
							</group>
						</group>
					</group>
				</group>
				<group name='Reference002' rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<group
						name='Hips_1'
						position={[0.12, 0.22, -0.88]}
						rotation={[-1.55, -0.13, 0.33]}>
						<group
							name='RightUpLeg_1'
							position={[-0.08, 0, 0]}
							rotation={[-0.12, 0.09, -0.42]}>
							<group
								name='RightLeg_1'
								position={[0, -0.43, 0]}
								rotation={[0.57, -0.11, 0.01]}>
								<group
									name='RightFoot_1'
									position={[0, -0.42, 0]}
									rotation={[0.14, -0.22, 0.03]}>
									<group
										name='RightToeBase_1'
										position={[0, -0.07, 0.15]}
										rotation={[-0.52, -0.06, 0.23]}
									/>
								</group>
							</group>
						</group>
						<group
							name='LeftUpLeg_1'
							position={[0.08, 0, 0]}
							rotation={[0.09, 0.12, -0.44]}>
							<group
								name='LeftLeg_1'
								position={[0, -0.43, 0]}
								rotation={[0.12, -0.03, -0.03]}>
								<group
									name='LeftFoot_1'
									position={[0, -0.42, 0]}
									rotation={[-0.24, 0.1, 0.22]}>
									<group name='LeftToeBase_1' position={[0, -0.07, 0.15]} />
								</group>
							</group>
						</group>
						<group
							name='Spine_1'
							position={[0, 0.1, -0.01]}
							rotation={[0.02, 0, -0.11]}>
							<group
								name='Spine1_1'
								position={[0, 0.11, 0]}
								rotation={[-0.09, 0.01, -0.05]}>
								<group
									name='Spine2_1'
									position={[0, 0.1, 0]}
									rotation={[0.01, 0.01, -0.05]}>
									<group
										name='Spine3_1'
										position={[0, 0.1, 0]}
										rotation={[0.11, 0, -0.04]}>
										<group
											name='LeftShoulder_1'
											position={[0.03, 0.08, 0]}
											rotation={[0.22, -0.16, -0.11]}>
											<group
												name='LeftArm_1'
												position={[0.14, 0, 0]}
												rotation={[-0.11, -0.5, -0.65]}>
												<group
													name='LeftForeArm_1'
													position={[0.31, 0, 0]}
													rotation={[0.11, -0.23, -0.1]}>
													<group
														name='LeftHand_1'
														position={[0.25, 0, 0]}
														rotation={[-0.06, 0.01, 0.27]}
													/>
												</group>
											</group>
										</group>
										<group
											name='RightShoulder_1'
											position={[-0.03, 0.08, 0]}
											rotation={[0.18, 0.09, -0.04]}>
											<group
												name='RightArm_1'
												position={[-0.14, 0, 0]}
												rotation={[0.09, 0.89, 0.85]}>
												<group
													name='RightForeArm_1'
													position={[-0.31, 0, 0]}
													rotation={[0.11, 0.3, 0]}>
													<group
														name='RightHand_1'
														position={[-0.25, 0, 0]}
														rotation={[0.11, 0.04, -0.09]}
													/>
												</group>
											</group>
										</group>
										<group
											name='Neck_1'
											position={[0, 0.14, 0]}
											rotation={[0.41, 0.16, -0.12]}>
											<group
												name='Head_1'
												position={[0, 0.09, 0]}
												rotation={[0.14, 0.32, -0.18]}
											/>
										</group>
									</group>
								</group>
							</group>
						</group>
					</group>
				</group>
				<group name='Reference003' rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<group
						name='Hips_2'
						position={[-0.09, -0.08, -1.03]}
						rotation={[-1.48, 0.49, 0.04]}>
						<group
							name='RightUpLeg_2'
							position={[-0.08, 0, 0]}
							rotation={[-0.89, -0.05, -0.18]}>
							<group
								name='RightLeg_2'
								position={[0, -0.43, 0]}
								rotation={[1.46, -0.23, 0.42]}>
								<group
									name='RightFoot_2'
									position={[0, -0.42, 0]}
									rotation={[-0.59, 0, -0.34]}>
									<group
										name='RightToeBase_2'
										position={[0, -0.07, 0.15]}
										rotation={[-0.06, 0, 0.16]}
									/>
								</group>
							</group>
						</group>
						<group
							name='LeftUpLeg_2'
							position={[0.08, 0, 0]}
							rotation={[-1.04, 0.31, 0.63]}>
							<group
								name='LeftLeg_2'
								position={[0, -0.43, 0]}
								rotation={[2, -0.14, -0.11]}>
								<group
									name='LeftFoot_2'
									position={[0, -0.42, 0]}
									rotation={[0.03, -0.14, -0.05]}>
									<group name='LeftToeBase_2' position={[0, -0.07, 0.15]} />
								</group>
							</group>
						</group>
						<group
							name='Spine_2'
							position={[0, 0.1, -0.01]}
							rotation={[0.12, -0.19, -0.02]}>
							<group
								name='Spine1_2'
								position={[0, 0.11, 0]}
								rotation={[-0.05, -0.08, -0.02]}>
								<group
									name='Spine2_2'
									position={[0, 0.1, 0]}
									rotation={[0.05, -0.08, -0.02]}>
									<group
										name='Spine3_2'
										position={[0, 0.1, 0]}
										rotation={[0.14, -0.06, -0.01]}>
										<group
											name='LeftShoulder_2'
											position={[0.03, 0.08, 0]}
											rotation={[0.37, -0.35, 0.05]}>
											<group
												name='LeftArm_2'
												position={[0.14, 0, 0]}
												rotation={[-0.28, -0.78, -0.3]}>
												<group
													name='LeftForeArm_2'
													position={[0.31, 0, 0]}
													rotation={[-0.78, -1.42, -0.68]}>
													<group
														name='LeftHand_2'
														position={[0.25, 0, 0]}
														rotation={[-0.18, 0.16, 0.24]}
													/>
												</group>
											</group>
										</group>
										<group
											name='RightShoulder_2'
											position={[-0.03, 0.08, 0]}
											rotation={[0.5, 0.05, -0.09]}>
											<group
												name='RightArm_2'
												position={[-0.14, 0, 0]}
												rotation={[0.08, 0.18, 0.42]}>
												<group
													name='RightForeArm_2'
													position={[-0.31, 0, 0]}
													rotation={[-2.83, 1.34, 2.29]}>
													<group
														name='RightHand_2'
														position={[-0.25, 0, 0]}
														rotation={[-0.27, 0, -0.14]}
													/>
												</group>
											</group>
										</group>
										<group
											name='Neck_2'
											position={[0, 0.14, 0]}
											rotation={[0.52, -0.01, -0.03]}>
											<group
												name='Head_2'
												position={[0, 0.09, 0]}
												rotation={[0.34, -0.01, -0.05]}
											/>
										</group>
									</group>
								</group>
							</group>
						</group>
					</group>
				</group>
				<group
					name='Reference'
					position={[0, -0.15, -0.03]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.25}>
					<primitive object={nodes.Hips_3} />
					<group name='_arm_R'>
						<skinnedMesh
							frustumCulled={false}
							name='Roundcube003'
							geometry={nodes.Roundcube003.geometry}
							material={materials["Metal scratched"]}
							skeleton={nodes.Roundcube003.skeleton}
						/>
						<skinnedMesh
							frustumCulled={false}
							name='Roundcube003_1'
							geometry={nodes.Roundcube003_1.geometry}
							material={materials["Metal blau"]}
							skeleton={nodes.Roundcube003_1.skeleton}
						/>
						<skinnedMesh
							frustumCulled={false}
							name='Roundcube003_2'
							geometry={nodes.Roundcube003_2.geometry}
							material={materials["boletes grogues"]}
							skeleton={nodes.Roundcube003_2.skeleton}
						/>
						<skinnedMesh
							frustumCulled={false}
							name='Roundcube003_3'
							geometry={nodes.Roundcube003_3.geometry}
							material={materials["Metal.claret"]}
							skeleton={nodes.Roundcube003_3.skeleton}
						/>
					</group>
					<group name='_LEG_R'>
						<skinnedMesh
							frustumCulled={false}
							name='Cylinder001'
							geometry={nodes.Cylinder001.geometry}
							material={materials["Metal scratched"]}
							skeleton={nodes.Cylinder001.skeleton}
						/>
						<skinnedMesh
							frustumCulled={false}
							name='Cylinder001_1'
							geometry={nodes.Cylinder001_1.geometry}
							material={materials["Metal.claret"]}
							skeleton={nodes.Cylinder001_1.skeleton}
						/>
					</group>
					<group name='arm_L'>
						<skinnedMesh
							frustumCulled={false}
							name='Roundcube001'
							geometry={nodes.Roundcube001.geometry}
							material={materials["Metal scratched"]}
							skeleton={nodes.Roundcube001.skeleton}
						/>
						<skinnedMesh
							frustumCulled={false}
							name='Roundcube001_1'
							geometry={nodes.Roundcube001_1.geometry}
							material={materials["Metal blau"]}
							skeleton={nodes.Roundcube001_1.skeleton}
						/>
						<skinnedMesh
							frustumCulled={false}
							name='Roundcube001_2'
							geometry={nodes.Roundcube001_2.geometry}
							material={materials["boletes grogues"]}
							skeleton={nodes.Roundcube001_2.skeleton}
						/>
						<skinnedMesh
							frustumCulled={false}
							name='Roundcube001_3'
							geometry={nodes.Roundcube001_3.geometry}
							material={materials["Metal.claret"]}
							skeleton={nodes.Roundcube001_3.skeleton}
						/>
					</group>
					<group name='Body'>
						<skinnedMesh
							frustumCulled={false}
							name='Roundcube008'
							geometry={nodes.Roundcube008.geometry}
							material={materials["Metal scratched"]}
							skeleton={nodes.Roundcube008.skeleton}
						/>
						<skinnedMesh
							frustumCulled={false}
							name='Roundcube008_1'
							geometry={nodes.Roundcube008_1.geometry}
							material={materials["Metal blau"]}
							skeleton={nodes.Roundcube008_1.skeleton}
						/>
						<skinnedMesh
							frustumCulled={false}
							name='Roundcube008_2'
							geometry={nodes.Roundcube008_2.geometry}
							material={materials["Metal.claret"]}
							skeleton={nodes.Roundcube008_2.skeleton}
						/>
					</group>
					<skinnedMesh
						frustumCulled={false}
						name='ears'
						geometry={nodes.ears.geometry}
						material={materials.Material}
						skeleton={nodes.ears.skeleton}>
						<meshPhongMaterial color={0x990d42} />
					</skinnedMesh>
					<group name='head'>
						<skinnedMesh
							frustumCulled={false}
							name='Sphere004'
							geometry={nodes.Sphere004.geometry}
							skeleton={nodes.Sphere004.skeleton}>
							<meshPhongMaterial color={0x990d42} />
						</skinnedMesh>
						<skinnedMesh
							frustumCulled={false}
							name='Sphere004_1'
							geometry={nodes.Sphere004_1.geometry}
							material={materials["Material.002"]}
							skeleton={nodes.Sphere004_1.skeleton}
						/>
						<skinnedMesh
							frustumCulled={false}
							name='coin_'
							geometry={nodes.coin_.geometry}
							material={materials["Fine Gold"]}
							skeleton={nodes.coin_.skeleton}
						/>
						<skinnedMesh
							frustumCulled={false}
							name='coin_001'
							geometry={nodes.coin_001.geometry}
							material={materials["Fine Gold"]}
							skeleton={nodes.coin_001.skeleton}
						/>
					</group>
					<group name='LEG_L'>
						<skinnedMesh
							frustumCulled={false}
							name='Cylinder002'
							geometry={nodes.Cylinder002.geometry}
							material={materials["Metal scratched"]}
							skeleton={nodes.Cylinder002.skeleton}
						/>
						<skinnedMesh
							frustumCulled={false}
							name='Cylinder002_1'
							geometry={nodes.Cylinder002_1.geometry}
							material={materials["Metal.claret"]}
							skeleton={nodes.Cylinder002_1.skeleton}
						/>
					</group>
				</group>
				<mesh
					name='StaffSPLINE'
					geometry={nodes.StaffSPLINE.geometry}
					material={materials["Fine Gold"]}
					position={[0.27, 0.23, -0.07]}
					rotation={[2.6, -0.83, 1.02]}
					scale={0.57}>
					<mesh
						name='Sphere'
						geometry={nodes.Sphere.geometry}
						material={materials["Fine Gold"]}
						position={[0, 0, -0.01]}
					/>
					<mesh
						name='Spiral'
						geometry={nodes.Spiral.geometry}
						material={materials["Fine Gold"]}
						position={[0, 0, 0.33]}
						rotation={[0, 0, Math.PI / 2]}
					/>
				</mesh>
			</group>
		</group>
	);
}

useGLTF.preload("/AmbuTricks.glb");
