/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import * as THREE from "three";
export function AmbuBtwist(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF("/AmbuBtwist.glb");
	const { actions } = useAnimations(animations, group);

	console.log(actions);
	actions["Btwist"].play();
	useEffect(() => {}, []);
	return (
		<group scale={6} ref={group} {...props} dispose={null}>
			<group name='Scene'>
				<group
					name='terreno_pincy'
					position={[-0.52, -0.79, 0.41]}
					rotation={[0, 0, -0.06]}
				/>
				<group
					name='Reference'
					position={[0, -0.15, -0.43]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.25}>
					<primitive object={nodes.Hips} />
					<group name='arm_L'>
						<skinnedMesh
							name='Roundcube001'
							geometry={nodes.Roundcube001.geometry}
							material={materials["Metal scratched"]}
							skeleton={nodes.Roundcube001.skeleton}
						/>
						<skinnedMesh
							name='Roundcube001_1'
							geometry={nodes.Roundcube001_1.geometry}
							material={materials["Metal blau"]}
							skeleton={nodes.Roundcube001_1.skeleton}
						/>
						<skinnedMesh
							name='Roundcube001_2'
							geometry={nodes.Roundcube001_2.geometry}
							material={materials["boletes grogues"]}
							skeleton={nodes.Roundcube001_2.skeleton}
						/>
						<skinnedMesh
							name='Roundcube001_3'
							geometry={nodes.Roundcube001_3.geometry}
							material={materials["Metal.claret"]}
							skeleton={nodes.Roundcube001_3.skeleton}
						/>
					</group>
					<group name='_arm_R'>
						<skinnedMesh
							name='Roundcube003'
							geometry={nodes.Roundcube003.geometry}
							material={materials["Metal scratched"]}
							skeleton={nodes.Roundcube003.skeleton}
						/>
						<skinnedMesh
							name='Roundcube003_1'
							geometry={nodes.Roundcube003_1.geometry}
							material={materials["Metal blau"]}
							skeleton={nodes.Roundcube003_1.skeleton}
						/>
						<skinnedMesh
							name='Roundcube003_2'
							geometry={nodes.Roundcube003_2.geometry}
							material={materials["boletes grogues"]}
							skeleton={nodes.Roundcube003_2.skeleton}
						/>
						<skinnedMesh
							name='Roundcube003_3'
							geometry={nodes.Roundcube003_3.geometry}
							material={materials["Metal.claret"]}
							skeleton={nodes.Roundcube003_3.skeleton}
						/>
					</group>
					<group name='_LEG_R'>
						<skinnedMesh
							name='Cylinder001'
							geometry={nodes.Cylinder001.geometry}
							material={materials["Metal scratched"]}
							skeleton={nodes.Cylinder001.skeleton}
						/>
						<skinnedMesh
							name='Cylinder001_1'
							geometry={nodes.Cylinder001_1.geometry}
							material={materials["Metal.claret"]}
							skeleton={nodes.Cylinder001_1.skeleton}
						/>
					</group>
					<group name='Body'>
						<skinnedMesh
							name='Roundcube008'
							geometry={nodes.Roundcube008.geometry}
							material={materials["Metal scratched"]}
							skeleton={nodes.Roundcube008.skeleton}
						/>
						<skinnedMesh
							name='Roundcube008_1'
							geometry={nodes.Roundcube008_1.geometry}
							material={materials["Metal blau"]}
							skeleton={nodes.Roundcube008_1.skeleton}
						/>
						<skinnedMesh
							name='Roundcube008_2'
							geometry={nodes.Roundcube008_2.geometry}
							material={materials["Metal.claret"]}
							skeleton={nodes.Roundcube008_2.skeleton}
						/>
					</group>
					<skinnedMesh
						name='ears'
						geometry={nodes.ears.geometry}
						material={materials.Material}
						skeleton={nodes.ears.skeleton}
					/>
					<group name='head_1'>
						<skinnedMesh
							name='Sphere004'
							geometry={nodes.Sphere004.geometry}
							material={materials.Material}
							skeleton={nodes.Sphere004.skeleton}
						/>
						<skinnedMesh
							name='Sphere004_1'
							geometry={nodes.Sphere004_1.geometry}
							material={materials["Material.002"]}
							skeleton={nodes.Sphere004_1.skeleton}
						/>
						<skinnedMesh
							name='coin_'
							geometry={nodes.coin_.geometry}
							material={materials["Fine Gold"]}
							skeleton={nodes.coin_.skeleton}
						/>
						<skinnedMesh
							name='coin_001'
							geometry={nodes.coin_001.geometry}
							material={materials["Fine Gold"]}
							skeleton={nodes.coin_001.skeleton}
						/>
					</group>
					<group name='LEG_L'>
						<skinnedMesh
							name='Cylinder002'
							geometry={nodes.Cylinder002.geometry}
							material={materials["Metal scratched"]}
							skeleton={nodes.Cylinder002.skeleton}
						/>
						<skinnedMesh
							name='Cylinder002_1'
							geometry={nodes.Cylinder002_1.geometry}
							material={materials["Metal.claret"]}
							skeleton={nodes.Cylinder002_1.skeleton}
						/>
					</group>
				</group>
				<mesh
					name='StaffSPLINE'
					geometry={nodes.StaffSPLINE.geometry}
					material={materials["Fine Gold"]}
					position={[0.27, 0.23, -0.07]}
					rotation={[2.6, -0.83, 1.02]}
					scale={0.57}>
					<mesh
						name='Sphere'
						geometry={nodes.Sphere.geometry}
						material={materials["Fine Gold"]}
						position={[0, 0, -0.01]}
					/>
					<mesh
						name='Spiral'
						geometry={nodes.Spiral.geometry}
						material={materials["Fine Gold"]}
						position={[0, 0, 0.33]}
						rotation={[0, 0, Math.PI / 2]}
					/>
				</mesh>
			</group>
		</group>
	);
}

useGLTF.preload("/AmbuBtwist.glb");
